// Contenido del Capítulo 1: mapas mentales, mnemotecnias, tarjetas, perspectivas y banco de 60 preguntas.
const DATA=[
{n:1,name:'Los psicólogos en acción',center:'Psicología: ciencia del comportamiento y los procesos mentales',
 branches:[
 ['Neurociencia conductual','Cómo el cerebro, el sistema nervioso y otros procesos biológicos determinan el comportamiento.','Ejemplo: vínculo entre sitios del cerebro y los temblores del Parkinson.'],
 ['Psicología experimental','Estudia sensación, percepción, aprendizaje y pensamiento. De ella nace la psicología cognitiva (memoria, razonamiento, lenguaje, decisiones).','Ejemplo: por qué caemos en ilusiones ópticas; escribir y manejar a la vez deteriora la conducción.'],
 ['Desarrollo y personalidad','Desarrollo: crecimiento y cambio desde la concepción hasta la muerte. Personalidad: consistencia del comportamiento y rasgos que distinguen a cada persona.','Ejemplo: primera sonrisa, primeros pasos, primera palabra.'],
 ['Salud, clínica y orientación','Salud: relación entre factores psicológicos y enfermedades físicas. Clínica: estudio, diagnóstico y tratamiento de trastornos. Orientación: problemas educativos, sociales y laborales, más específicos.','Ejemplo: efecto del estrés en la salud a largo plazo.'],
 ['Social e intercultural','Social: influencia de pensamientos, sentimientos y acciones de unos en otros. Intercultural: semejanzas y diferencias entre culturas y grupos étnicos.','Ejemplo: agresividad, amor, persuasión, obediencia; uso del castigo en la crianza según la cultura.'],
 ['Nuevas fronteras','Evolutiva: herencia genética de los ancestros (Darwin, selección natural). Genética conductual: genes y cromosomas. Neuropsicología clínica: une neurociencia y psicología clínica.','Ejemplo: la timidez o los celos podrían tener raíz genética y ayudar a la supervivencia.'],
 ['Dónde trabajan','Mayoría en ambientes académicos; también práctica privada, hospitales, clínicas, escuelas, empresas, gobierno y prisiones. Tres roles: maestro, científico y profesional clínico.','Ejemplo: consultor industrial-organizacional en una empresa.']],
 mn:{title:'Cada Mente Vive Sana y Social: las cinco preguntas que ordenan los subcampos',tiles:[['C','Cerebro','Neurociencia conductual'],['M','Mundo','Experimental y cognitiva'],['V','Vida','Desarrollo y personalidad'],['S','Sana','Salud, clínica y orientación'],['S','Social','Social e intercultural']],tip:'Roles del psicólogo: Maestro, Científico, Clínico (MCC).'},
 cards:[['Definición','¿Qué es la psicología?','Estudio científico del comportamiento y los procesos mentales.'],['Contraste','Psicología clínica vs. orientación psicológica','Clínica: trastornos, de crisis cotidianas a depresión profunda. Orientación: problemas educativos, sociales y de adaptación profesional.'],['Evolutiva','¿En qué se apoya la psicología evolutiva?','En Darwin y la selección natural: rasgos y conductas que ayudaron a sobrevivir y reproducirse. Se critica que minimiza el ambiente.']]},
{n:2,name:'Una ciencia evoluciona',center:'Enfoques de la psicología',
 branches:[
 ['Estructuralismo','Wundt y Titchener: dividir la mente en sus componentes básicos mediante la introspección.','Clave: la estructura, las piezas.'],
 ['Funcionalismo','William James: qué función cumplen la mente y el comportamiento para adaptarse al ambiente.','Clave: para qué sirve.'],
 ['Psicología Gestalt','Percibimos patrones y totalidades, no solo elementos aislados.','Clave: el todo.'],
 ['Neurociencia','Conducta explicada por procesos biológicos: cerebro, genes, hormonas.','Clave: sangre, sudor y miedos.'],
 ['Psicodinámica','Freud: fuerzas inconscientes internas, impulsos y conflictos de la infancia.','Clave: la persona interna.'],
 ['Conductual','Solo la conducta observable, moldeada por el ambiente y el aprendizaje.','Clave: la persona externa.'],
 ['Cognitiva','Cómo pensamos, comprendemos, recordamos y procesamos la información.','Clave: las raíces de la comprensión.'],
 ['Humanista','Cualidades únicas de la especie: libre albedrío y búsqueda del potencial propio.','Clave: elección y crecimiento.']],
 mn:{title:'Niños Pequeños Comen Cereal Hoy: las cinco perspectivas actuales',tiles:[['N','Neurociencia','Biología del comportamiento'],['P','Psicodinámica','Fuerzas inconscientes'],['C','Conductual','Conducta observable'],['C','Cognitiva','Pensamiento y memoria'],['H','Humanista','Libre albedrío y potencial']],tip:'Escuelas tempranas: Estructuralismo = Estructura (piezas); Funcionalismo = Función; Gestalt = Global. Controversias: naturaleza-crianza, consciente-inconsciente, libre albedrío-determinismo, observable-interno, estabilidad-cambio.'},
 cards:[['Contraste','Estructuralismo vs. funcionalismo','Estructuralismo: componentes de la mente por introspección. Funcionalismo: para qué sirven la mente y la conducta.'],['Controversia','Libre albedrío vs. determinismo','Libre albedrío: elegimos nuestros actos. Determinismo: factores fuera de nuestro control los determinan.'],['Perspectiva','¿Qué estudia la perspectiva cognitiva?','Cómo las personas piensan, comprenden y conciben el mundo.']]},
{n:3,name:'La investigación en la psicología',center:'Método científico',
 branches:[
 ['Teorías','Explicaciones generales de un fenómeno de interés.','Se concretan en hipótesis.'],
 ['Hipótesis','Predicciones comprobables derivadas de una teoría; requieren una definición operacional.','Se ponen a prueba con investigación.'],
 ['Investigación documental','Examinar registros existentes para poner a prueba una hipótesis.','Riesgo: pueden no existir datos o ser inútiles.'],
 ['Observación naturalista','Observar el comportamiento en su ambiente real sin intervenir.','Riesgo: la gente cambia si sabe que la observan.'],
 ['Encuestas','Preguntar directamente a una muestra de personas sobre su comportamiento.','Riesgo: la gente puede mentir para dar buena imagen.'],
 ['Estudio de caso','Investigación profunda de una persona o grupo pequeño.','Limitado para generalizar.'],
 ['Correlacional','Busca si dos variables se relacionan.','Correlación no implica causalidad.'],
 ['Experimental','Manipula una variable y asigna al azar a grupo experimental y grupo control.','Única que establece causa y efecto.']],
 mn:{title:'Don Nicolás Enseña Casos Con Experimentos: los seis métodos',tiles:[['D','Documental','Registros existentes'],['N','Naturalista','Observar sin intervenir'],['E','Encuesta','Preguntar a una muestra'],['C','Caso','Estudio profundo'],['C','Correlacional','Relación, no causa'],['E','Experimental','Manipular y controlar']],tip:'Variable Independiente: la que Impone el investigador. Variable Dependiente: Depende de lo que haga el participante.'},
 cards:[['Experimento','Grupo experimental vs. grupo control','El experimental recibe el tratamiento; el control no. La asignación aleatoria los hace comparables.'],['Variables','Independiente y dependiente','Independiente: la que manipula el experimentador. Dependiente: la que se mide como resultado.'],['Principio','¿Qué significa «correlación no implica causalidad»?','Dos variables relacionadas no prueban que una cause la otra.']]},
{n:4,name:'Cuestiones fundamentales',center:'Ética y validez de la investigación',
 branches:[
 ['Proteger del daño','Los participantes deben protegerse de daño físico y mental.','Ética de la investigación.'],
 ['Privacidad','Derecho de los participantes a la privacidad sobre su conducta.','Ética de la investigación.'],
 ['Participación voluntaria','La participación es completamente voluntaria; se puede abandonar en cualquier momento.','Ética de la investigación.'],
 ['Consentimiento informado','Antes de participar se informa el procedimiento general, los riesgos posibles y el derecho a retirarse.','Documento firmado por el participante.'],
 ['Diversidad','Elegir participantes que representen la diversidad del comportamiento humano.','Muestras representativas.'],
 ['Animales','Se debate su uso en la investigación; se pesan los beneficios frente al daño.','Pregunta abierta del módulo.'],
 ['Sesgo experimental','Factores que amenazan la validez del experimento; el placebo ayuda a controlarlo.','Ejemplo: participantes que se comportan según lo que creen esperado.']],
 mn:{title:'DPV: Daño, Privacidad, Voluntad',tiles:[['D','Daño','Proteger a los participantes'],['P','Privacidad','Resguardar su conducta'],['V','Voluntad','Participación libre']],tip:'Consentimiento informado = Procedimiento + Riesgos + Retiro.'},
 cards:[['Ética','¿Qué incluye el consentimiento informado?','Procedimiento general, riesgos posibles y derecho a retirarse en cualquier momento.'],['Definición','¿Qué es un placebo?','Tratamiento sin efecto activo usado para controlar el sesgo experimental.'],['Diversidad','¿Por qué usar participantes representativos?','Para que los resultados reflejen la diversidad del comportamiento humano.']]}
];
const SUM=[
{points:['La psicología es el estudio científico del comportamiento y los procesos mentales: incluye lo que la gente hace, pero también pensamientos, emociones, percepciones, recuerdos y actividad biológica.','Sus metas: describir, predecir y explicar el comportamiento, y ayudar a mejorar la vida de las personas.','Usa métodos científicos, más válidos que la intuición y la especulación.','Los subcampos son como un árbol genealógico: distintos entre sí, unidos por la meta de entender el comportamiento.','La mayoría de los psicólogos trabaja en ambientes académicos, donde combina los roles de maestro, científico y clínico.'],tips:['Alerta de estudio: conocer los subcampos permite ver un mismo comportamiento desde distintas expresiones.','«Experimental» engaña: psicólogos de todas las especialidades usan técnicas experimentales.','Al estudiar, asocie cada subcampo con su pregunta guía (cerebro, mundo, vida, salud, social).']},
{points:['La psicología nació de la introspección y de tres escuelas tempranas: estructuralismo, funcionalismo y Gestalt.','Hoy hay cinco perspectivas principales: neurociencia, psicodinámica, conductual, cognitiva y humanista.','Ninguna perspectiva es la única correcta: cada una explica el mismo comportamiento desde un ángulo distinto.','Las controversias fundamentales: naturaleza-crianza, consciente-inconsciente, libre albedrío-determinismo, observable-interno y estabilidad-cambio.','Hubo mujeres fundadoras de la psicología, a menudo poco reconocidas.'],tips:['Alerta de estudio: aprenda las perspectivas comparando cómo cada una explicaría una misma conducta.','Relacione cada perspectiva con una figura o frase clave (Freud: psicodinámica; James: funcionalismo).','Naturaleza-crianza: la mayoría de los psicólogos hoy acepta que ambas influyen.']},
{points:['El método científico: identificar preguntas, formular explicaciones, llevar a cabo la investigación y comunicar los resultados.','Una teoría explica en general; una hipótesis es una predicción comprobable, con definición operacional.','Investigación descriptiva: documental, observación naturalista, encuestas y estudio de caso.','Solo el experimento permite concluir causa y efecto: variable independiente (manipulada), variable dependiente (medida), grupo experimental, grupo control y asignación aleatoria.','Un resultado significativo y la réplica de la investigación dan confianza en los hallazgos.'],tips:['Alerta de estudio: «correlación no implica causalidad» es un principio clave.','Para cada método, memorice también su debilidad (datos inútiles, observados que cambian, mentiras en encuestas).','Pregunta de repaso: ¿qué cambió el investigador y qué se midió?']},
{points:['La ética de la investigación protege a los participantes: del daño, en su privacidad y con participación voluntaria.','El consentimiento informado incluye procedimiento, riesgos y el derecho a retirarse en cualquier momento.','Los participantes deben representar la diversidad del comportamiento humano.','El uso de animales se debate pesando beneficios y daño.','El sesgo experimental amenaza la validez; el placebo ayuda a controlarlo.'],tips:['Alerta de estudio: para elegir la respuesta ética, busque protección, voluntariedad e información completa.','Ser consumidor informado de la psicología significa pensar críticamente: ¿quién investigó, con qué muestra y qué método?','Cuidado con «todas las anteriores»: en consentimiento informado, procedimiento, riesgos y retiro van juntos.']}
];
const EXTRA=[
[['Neurociencia','¿Qué estudia la neurociencia conductual?','Cómo el cerebro, el sistema nervioso y otros procesos biológicos determinan el comportamiento.'],['Desarrollo','Psicología del desarrollo vs. de la personalidad','Desarrollo: crecimiento y cambio de la concepción a la muerte. Personalidad: consistencia del comportamiento y rasgos que distinguen a las personas.'],['Social','Psicología social vs. intercultural','Social: influencia de los pensamientos, sentimientos y acciones de unos en otros. Intercultural: semejanzas y diferencias entre culturas y grupos étnicos.'],['Roles','¿Cuáles son los tres roles del psicólogo?','Maestro, científico y profesional clínico; la mayoría trabaja en ambientes académicos.'],['Fronteras','¿Qué estudia la genética conductual?','Los mecanismos biológicos, como genes y cromosomas, que permiten que se desarrolle el comportamiento heredado.'],['Cognitiva','¿Qué procesos estudia la psicología cognitiva?','Pensamiento, memoria, razonamiento, resolución de problemas, juicio, toma de decisiones y lenguaje.']],
[['Escuelas','¿Qué es el estructuralismo?','Dividir la mente en sus componentes básicos mediante la introspección (Wundt y Titchener).'],['Escuelas','¿Qué propone la psicología Gestalt?','Percibimos patrones y totalidades, no solo elementos aislados.'],['Perspectiva','¿Qué explica la perspectiva psicodinámica?','El comportamiento por fuerzas inconscientes internas; su figura clave es Freud.'],['Perspectiva','Conductual vs. humanista','Conductual: solo la conducta observable, moldeada por el ambiente. Humanista: libre albedrío y búsqueda del potencial propio.'],['Controversia','Naturaleza vs. crianza','¿Pesa más la herencia o el ambiente? La mayoría acepta que ambos influyen.'],['Término','¿Qué es la introspección?','Método en el que las personas describen lo que experimentan en su mente; base del estructuralismo.']],
[['Método','¿Cuáles son los pasos del método científico?','Identificar preguntas, formular explicaciones, llevar a cabo la investigación y comunicar los resultados.'],['Conceptos','Teoría vs. hipótesis','Teoría: explicación general de un fenómeno. Hipótesis: predicción comprobable derivada de la teoría.'],['Descriptiva','¿Qué es la observación naturalista?','Observar el comportamiento en su ambiente real sin intervenir. Debilidad: la gente cambia si sabe que la observan.'],['Descriptiva','¿Y la investigación por encuestas?','Preguntar directamente a una muestra sobre su comportamiento. Debilidad: la gente puede mentir para dar buena imagen.'],['Experimento','¿Para qué sirve la asignación aleatoria?','Para que cada participante tenga la misma probabilidad de quedar en cualquier condición y los grupos sean comparables.'],['Experimento','¿Qué es una definición operacional?','Traducir la hipótesis a procedimientos concretos que se pueden medir o manipular.']],
[['Ética','¿Qué tres derechos protege la ética?','Protección contra daño físico y mental, privacidad sobre su conducta y participación completamente voluntaria.'],['Validez','¿Qué es el sesgo experimental?','Factores que amenazan la validez del experimento, como las expectativas de los participantes o del experimentador.'],['Animales','¿Qué se debate sobre el uso de animales?','Si los beneficios de la investigación justifican el posible daño a los animales.'],['Consumidor','¿Qué es ser consumidor informado de la psicología?','Pensar críticamente: preguntar quién investigó, con qué muestra y con qué método.'],['Ética','¿Puede un participante abandonar el estudio?','Sí, en cualquier momento; es parte del consentimiento informado.'],['Diversidad','Participantes representativos','Elegirlos asegura que los hallazgos describan la diversidad del comportamiento humano y no solo a un grupo.']]
];
const LENS=[['Neurociencia','Cerebro y biología'],['Psicodinámica','Fuerzas inconscientes'],['Conductual','Conducta aprendida'],['Cognitiva','Pensamientos'],['Humanista','Potencial y elección']];
const PERS=[
['Neurociencia','Sangre, sudor y miedos','El comportamiento se explica por procesos biológicos del cuerpo.','¿Qué pasa en mi cerebro y mi cuerpo?','Cerebro, sistema nervioso, genes y hormonas.','Roger Sperry · Donald Hebb'],
['Psicodinámica','La persona interna','Fuerzas inconscientes internas, en gran parte de la infancia, motivan la conducta (Freud).','¿Qué impulsos ocultos me mueven?','El inconsciente y los conflictos internos.','Sigmund Freud · Carl Jung · Erik Erikson'],
['Conductual','La persona externa','Lo que importa es la conducta observable, moldeada por el ambiente y el aprendizaje.','¿Qué conducta se ve y qué la refuerza?','Estímulos, respuestas y consecuencias.','John B. Watson · B. F. Skinner · Ivan Pavlov'],
['Cognitiva','Las raíces de la comprensión','Cómo las personas piensan, comprenden y conciben el mundo.','¿Cómo interpreto y proceso la información?','Pensamiento, memoria, razonamiento y lenguaje.','Jean Piaget · Ulric Neisser'],
['Humanista','Cualidades únicas de la especie','Las personas eligen con libre albedrío y buscan desarrollar su potencial.','¿Qué elijo y qué puedo llegar a ser?','Libre albedrío, crecimiento y valoración personal.','Carl Rogers · Abraham Maslow']
];
const SCENES=[
{label:'Miedo a hablar en público',t:['Activación del sistema nervioso: el corazón se acelera y el cerebro responde como ante una amenaza.','Conflictos inconscientes o experiencias de la infancia que se expresan como ansiedad.','Una experiencia vergonzosa asociada al hablar; la evitación refuerza el miedo.','Pensamientos como «me van a juzgar» que distorsionan cómo se interpreta la situación.','Necesidad de aceptación y de crecer; el miedo frena el potencial de la persona.']},
{label:'Un estudiante agresivo',t:['Factores biológicos: química cerebral, hormonas o genes que influyen en la agresividad.','Impulsos y conflictos internos reprimidos que salen en forma de hostilidad.','Conducta aprendida por imitación o porque fue reforzada en su entorno.','Interpreta las acciones de otros como hostiles y cree que la agresión resuelve los problemas.','Busca valoración y respeto; puede elegir otras formas de actuar con apoyo adecuado.']},
{label:'Dificultad para dormir',t:['Alteración de procesos biológicos que regulan el sueño, como la actividad cerebral y las hormonas.','Preocupaciones y deseos inconscientes que perturban el descanso.','Hábitos asociados a la cama (pantallas, horarios) que mantienen el insomnio.','Pensamientos repetitivos sobre las tareas pendientes o sobre no poder dormir.','Insatisfacción con la propia vida o con metas personales que mantiene a la persona inquieta.']}
];
const MORE=[
['Ubica su estudio en la biología: cuerpo y cerebro como base de la conducta.','Se confunde con «experimental»: aquí el énfasis está en lo cognitivo y perceptivo; todas las ramas usan experimentos.','Desarrollo = cambio a lo largo de la vida; personalidad = lo que permanece estable.','Tres ramas para tres tipos de problema: salud (enfermedad física), clínica (trastornos), orientación (dificultades más específicas).','Social estudia a la persona con los demás; intercultural compara entre culturas.','La evolutiva y la genética conductual generan debate porque pueden minimizar la influencia del ambiente.','Maestro, Científico, Clínico: los tres roles se combinan en el ambiente académico.'],
['Estructuralismo describe las piezas de la mente; el método era la introspección.','Funcionalismo pregunta «¿para qué sirve?»; lo representa William James.','Gestalt: el todo es más que la suma de sus partes.','Es la perspectiva más «biológica» de las cinco.','Mire hacia dentro: motivos que la persona misma no reconoce.','Solo cuenta lo que se puede observar y medir de la conducta.','Hoy domina gran parte de la investigación sobre memoria, pensamiento y lenguaje.','Se opone al determinismo: la persona puede elegir.'],
['Una buena teoría genera hipótesis que se pueden comprobar.','Si no se puede medir u observar, no es comprobable: por eso se define operacionalmente.','Útil cuando ya existen registros; su límite es la calidad de los datos.','Observe sin que se note: lo ideal es que el sujeto no cambie su conducta.','El tamaño y la representatividad de la muestra importan.','Aporta profundidad pero poca capacidad de generalización.','Una relación fuerte no prueba causa; puede haber una tercera variable.','Es el único método que controla variables y permite hablar de causa y efecto.'],
['Piense en tres palabras: daño, privacidad, voluntad.','La privacidad protege lo que el participante hace y dice en el estudio.','Voluntario significa también poder salir en cualquier momento.','Procedimiento + riesgos + derecho a retirarse.','Un estudio con un solo grupo social no representa a todos.','Debate abierto: valorar beneficios científicos frente al daño a los animales.','El placebo permite separar el efecto real del efecto de la expectativa.']
];
const QB=[
{m:0,area:'Definición de la psicología',q:'La psicología se define como el estudio científico de:',o:['Solo la conducta observable','El comportamiento y los procesos mentales','Únicamente las enfermedades mentales','La intuición y la especulación'],a:1,e:'Incluye lo que la gente hace y también pensamientos, emociones, percepciones y recuerdos.'},
{m:0,area:'Subcampos: neurociencia conductual',q:'¿Qué subcampo examina cómo el cerebro y el sistema nervioso determinan el comportamiento?',o:['Psicología social','Orientación psicológica','Neurociencia conductual','Psicología de la personalidad'],a:2,e:'La neurociencia conductual estudia las bases biológicas del comportamiento.'},
{m:0,area:'Clínica vs. orientación psicológica',q:'Un centro universitario ayuda a estudiantes con métodos de estudio y elección de empleo. ¿Qué tipo de psicólogo trabaja allí?',o:['Orientador psicológico','Psicólogo evolutivo','Genetista conductual','Neuropsicólogo clínico'],a:0,e:'La orientación psicológica atiende problemas educativos, sociales y de adaptación profesional.'},
{m:0,area:'Roles y lugares de trabajo',q:'¿Cuáles son los tres roles principales del psicólogo en la sociedad?',o:['Terapeuta, juez y asesor','Maestro, científico y profesional clínico','Investigador, gerente y orientador','Consultor, escritor y médico'],a:1,e:'Muchos los combinan en ambientes académicos.'},
{m:1,area:'Escuelas tempranas',q:'El estructuralismo buscaba:',o:['Estudiar para qué sirve la mente','Percibir totalidades y patrones','Dividir la mente en componentes básicos mediante la introspección','Medir solo la conducta observable'],a:2,e:'Wundt y Titchener analizaban la estructura de la mente; el funcionalismo preguntaba por su función.'},
{m:1,area:'Perspectivas: psicodinámica',q:'¿Qué perspectiva explica la conducta por fuerzas inconscientes internas?',o:['Cognitiva','Conductual','Humanista','Psicodinámica'],a:3,e:'Es la perspectiva asociada con Freud.'},
{m:1,area:'Perspectivas: conductual',q:'La perspectiva que se limita a la conducta observable, moldeada por el ambiente, es la:',o:['Conductual','Neurociencia','Cognitiva','Humanista'],a:0,e:'La conductual pone atención en la «persona externa».'},
{m:1,area:'Controversias fundamentales',q:'La controversia «libre albedrío vs. determinismo» pregunta:',o:['Si pesa más la herencia o el ambiente','Si las personas eligen sus actos o los determinan factores fuera de su control','Si la conducta es estable o cambia','Si lo consciente importa más que lo inconsciente'],a:1,e:'La opción sobre herencia y ambiente es naturaleza-crianza.'},
{m:2,area:'Teorías e hipótesis',q:'Una explicación general de un fenómeno de interés se llama:',o:['Hipótesis','Réplica','Teoría','Variable'],a:2,e:'La hipótesis es una predicción comprobable derivada de la teoría.'},
{m:2,area:'Métodos descriptivos',q:'¿Qué método consiste en observar el comportamiento en su ambiente real sin intervenir?',o:['Estudio de caso','Observación naturalista','Investigación por encuestas','Investigación documental'],a:1,e:'Su debilidad: las personas pueden cambiar su conducta si saben que las observan.'},
{m:2,area:'Correlación y causalidad',q:'«Correlación no implica causalidad» significa que:',o:['Dos variables relacionadas no prueban que una cause la otra','Las correlaciones nunca son útiles','Solo las encuestas pueden mostrar causas','Una correlación alta demuestra la causa'],a:0,e:'Solo el experimento permite concluir causa y efecto.'},
{m:2,area:'Experimentos y variables',q:'En un experimento, la variable que el investigador manipula es la:',o:['Dependiente','Controlada por el grupo','Aleatoria','Independiente'],a:3,e:'La dependiente es la que se mide como resultado.'},
{m:3,area:'Consentimiento informado',q:'El consentimiento informado incluye:',o:['Solo el procedimiento del estudio','El procedimiento, los riesgos y el derecho a retirarse','Solo los resultados esperados','El pago a los participantes'],a:1,e:'Procedimiento + riesgos + derecho a retirarse en cualquier momento.'},
{m:3,area:'Sesgo experimental y placebo',q:'¿Para qué sirve un placebo?',o:['Para aumentar la participación','Para identificar al grupo experimental','Para controlar el sesgo experimental','Para proteger la privacidad'],a:2,e:'Permite separar el efecto real del efecto de la expectativa.'},
{m:3,area:'Diversidad de participantes',q:'Elegir participantes representativos permite que los hallazgos:',o:['Reflejen la diversidad del comportamiento humano','Sean más rápidos de obtener','Se limiten a un solo grupo','Eviten el consentimiento'],a:0,e:'Una muestra de un solo grupo no representa a todos.'},
{m:0,area:'Subcampos: desarrollo',q:'La psicología del desarrollo estudia:',o:['Solo la infancia','El crecimiento y la transformación de las personas desde la concepción hasta la muerte','Los trastornos psicológicos','Las diferencias entre culturas'],a:1,e:'La personalidad, en cambio, se centra en la consistencia del comportamiento y los rasgos individuales.'},
{m:0,area:'Subcampos: salud',q:'¿Qué subcampo explora la relación entre factores psicológicos, como el estrés, y las enfermedades físicas?',o:['Psicología de la salud','Psicología experimental','Psicología intercultural','Genética conductual'],a:0,e:'Evalúa, por ejemplo, el efecto del estrés en la salud a largo plazo.'},
{m:0,area:'Subcampos: social e intercultural',q:'La psicología social se ocupa de:',o:['Los mecanismos de genes y cromosomas','La influencia de los pensamientos, sentimientos y acciones de las personas en los demás','El diagnóstico de trastornos','Los procesos de sensación y percepción'],a:1,e:'Estudia temas como agresividad, amor, persuasión y obediencia.'},
{m:0,area:'Psicología evolutiva',q:'La psicología evolutiva parte de los argumentos de:',o:['Sigmund Freud','William James','Charles Darwin','Wilhelm Wundt'],a:2,e:'Plantea que la herencia genética influye en rasgos y conductas que ayudaron a sobrevivir.'},
{m:1,area:'Escuelas tempranas: funcionalismo',q:'El funcionalismo, impulsado por William James, se preguntaba:',o:['Cuáles son los elementos básicos de la mente','Qué función cumplen la mente y la conducta para adaptarse al ambiente','Cómo se perciben las totalidades','Qué ocurre en el inconsciente'],a:1,e:'El estructuralismo analizaba las piezas; el funcionalismo, su utilidad.'},
{m:1,area:'Perspectivas: humanista',q:'La perspectiva humanista destaca:',o:['La actividad cerebral','El libre albedrío y la búsqueda del potencial propio','Las fuerzas inconscientes','El procesamiento de información'],a:1,e:'Resalta las cualidades únicas de la especie humana.'},
{m:1,area:'Escuelas tempranas: Gestalt',q:'La psicología Gestalt sostiene que:',o:['La mente se divide en elementos mínimos','Solo importa la conducta observable','Percibimos patrones y totalidades, no solo elementos aislados','Los impulsos infantiles guían la conducta'],a:2,e:'Su idea clave es que el todo es más que la suma de las partes.'},
{m:1,area:'Controversias fundamentales',q:'La controversia «naturaleza-crianza» plantea:',o:['Si la conducta es observable o interna','Si pesa más la herencia o el ambiente en el comportamiento','Si somos libres o determinados','Si el cambio es posible'],a:1,e:'La mayoría de los psicólogos acepta que ambos influyen.'},
{m:2,area:'Teorías e hipótesis',q:'Una hipótesis es:',o:['Una explicación general de un fenómeno','Una predicción comprobable derivada de una teoría','El resultado final de un experimento','Un grupo de participantes'],a:1,e:'Para comprobarla se necesita una definición operacional.'},
{m:2,area:'Métodos descriptivos',q:'¿Cuál es una debilidad de la investigación por encuestas?',o:['Los participantes no responden nunca','La gente puede mentir para dar buena imagen','Solo sirve para un caso','Altera el ambiente natural'],a:1,e:'La observación naturalista, en cambio, puede alterar la conducta de quien se sabe observado.'},
{m:2,area:'Experimentos: grupos',q:'En un experimento, el grupo de control:',o:['Recibe el tratamiento','Es el que el investigador manipula','No recibe el tratamiento y sirve de comparación','Se elige siempre sin azar'],a:2,e:'El grupo experimental es el que recibe el tratamiento.'},
{m:2,area:'Experimentos: asignación aleatoria',q:'La asignación aleatoria significa que:',o:['Cada participante tiene la misma probabilidad de quedar en cualquier condición','Los participantes eligen su grupo','Solo se observan casos extremos','El investigador decide quién recibe el tratamiento'],a:0,e:'Así los grupos son comparables al comienzo.'},
{m:3,area:'Ética: protección del daño',q:'Una de las pautas éticas básicas es proteger a los participantes de:',o:['Cualquier pregunta','Daño físico y mental','La privacidad','Los resultados'],a:1,e:'Junto con la privacidad y la participación voluntaria.'},
{m:3,area:'Ética: participación voluntaria',q:'Participar en una investigación debe ser:',o:['Obligatorio si el estudio es importante','Completamente voluntario','Voluntario solo al inicio','Decidido por el investigador'],a:1,e:'El participante puede retirarse en cualquier momento.'},
{m:3,area:'Animales en la investigación',q:'El debate sobre el uso de animales en la investigación psicológica consiste en:',o:['Si los animales pueden dar consentimiento','Si los beneficios de la investigación justifican el posible daño','Si deben usarse en vez de personas siempre','Si su conducta es igual a la humana'],a:1,e:'Es una pregunta abierta en el módulo 4.'}
];
const mk=(m,area,q,r,w,e)=>({m,area,q,o:[r,...w],a:0,e});
QB.push(
mk(0,'Metas de la psicología','¿Cuáles son metas de los psicólogos?','Describir, predecir y explicar el comportamiento y los procesos mentales, y ayudar a mejorar la vida de las personas',['Solo diagnosticar trastornos','Únicamente observar animales','Reemplazar a la intuición con la especulación'],'Además, usan métodos científicos para obtener respuestas más válidas que la intuición.'),
mk(0,'Definición de la psicología','¿Por qué se prefieren los métodos científicos a la intuición y la especulación?','Porque producen respuestas más válidas y legítimas',['Porque son más rápidos','Porque evitan la observación','Porque no requieren datos'],'La intuición y la especulación suelen ser imprecisas.'),
mk(0,'Psicología cognitiva','La psicología cognitiva se concentra en:','Los procesos mentales superiores, como pensamiento, memoria, razonamiento y lenguaje',['Los genes y cromosomas','Los problemas de adaptación profesional','El crecimiento desde la concepción'],'Es una subespecialidad de la psicología experimental.'),
mk(0,'Psicología clínica','La psicología clínica se ocupa del:','Estudio, diagnóstico y tratamiento de los trastornos psicológicos',['Estudio de las diferencias entre culturas','Examen de la herencia de los ancestros','Asesoría sobre métodos de estudio'],'Va desde crisis cotidianas hasta condiciones como la depresión profunda.'),
mk(0,'Subcampos: personalidad','La psicología de la personalidad se concentra en:','La consistencia del comportamiento en el tiempo y los rasgos que diferencian a un individuo de otro',['La influencia de otros en la conducta','Los procesos de sensación y percepción','El tratamiento de trastornos'],'La del desarrollo estudia el cambio a lo largo de la vida.'),
mk(0,'Psicología social e intercultural','Un psicólogo que compara el uso del castigo en la crianza infantil entre culturas trabaja en la psicología:','Intercultural',['Experimental','De la salud','Clínica'],'La intercultural investiga semejanzas y diferencias entre culturas y grupos étnicos.'),
mk(0,'Genética conductual','La genética conductual se concentra en:','Los mecanismos biológicos, como genes y cromosomas, que permiten que se desarrolle el comportamiento heredado',['Los argumentos de la selección natural únicamente','La psicología del lenguaje','Los problemas educativos'],'También busca entender cuánto influye el ambiente en que se manifiesten los rasgos.'),
mk(0,'Roles y lugares de trabajo','¿Dónde trabaja la mayoría de los psicólogos?','En ambientes académicos',['Solo en prisiones','Únicamente en empresas','Solo en hospitales'],'Eso les permite combinar los roles de maestro, científico y profesional clínico.'),
mk(1,'Introspección','La introspección consiste en:','Que las personas describan lo que experimentan en su propia mente',['Observar la conducta externa','Medir la actividad cerebral','Analizar los sueños de otros'],'Fue el método del estructuralismo.'),
mk(1,'Perspectivas: neurociencia','La perspectiva de la neurociencia explica el comportamiento a partir de:','Procesos biológicos del cuerpo, como el cerebro y el sistema nervioso',['Fuerzas inconscientes','Pensamientos y recuerdos únicamente','El libre albedrío'],'Se describe como «sangre, sudor y miedos».'),
mk(1,'Perspectivas: cognitiva','La perspectiva cognitiva se interesa por:','Cómo las personas piensan, comprenden y conciben el mundo',['Solo la conducta observable','Los impulsos de la infancia','La búsqueda de la autorrealización'],'Se centra en los procesos mentales.'),
mk(1,'Perspectivas: psicodinámica','Sigmund Freud se asocia con la perspectiva:','Psicodinámica',['Conductual','Humanista','Cognitiva'],'Pone atención en la «persona interna» y el inconsciente.'),
mk(1,'Controversias: determinismo','El determinismo sostiene que:','Factores fuera de nuestro control determinan nuestras acciones',['Podemos elegir libremente todos nuestros actos','La conducta no tiene causas','Solo importa el ambiente actual'],'Es el polo opuesto del libre albedrío.'),
mk(1,'Controversias: consciente-inconsciente','¿Qué plantea la controversia «consciente vs. inconsciente»?','Si la conducta se explica por procesos que conocemos o por fuerzas de las que no nos damos cuenta',['Si los animales piensan','Si la herencia pesa más que el ambiente','Si las personas cambian con la edad'],'Se vincula con la perspectiva psicodinámica.'),
mk(1,'Perspectivas: varias miradas','¿Por qué hay varias perspectivas en la psicología contemporánea?','Porque cada una explica el mismo comportamiento desde un ángulo distinto',['Porque solo una es correcta','Porque se contradicen sin utilidad','Porque cada una estudia un animal distinto'],'Por eso la guía invita a comparar cómo cada una explicaría una misma conducta.'),
mk(1,'Controversias: estabilidad-cambio','La controversia «estabilidad vs. cambio» se pregunta si:','Las personas permanecen iguales o cambian a lo largo de la vida',['La conducta es heredada o aprendida','El inconsciente existe','Somos libres o determinados'],'Se relaciona con el desarrollo y la personalidad.'),
mk(2,'Método científico','¿Cuál es el primer paso del método científico?','Identificar preguntas de interés',['Comunicar los resultados','Llevar a cabo la investigación','Replicar el estudio'],'Luego se formulan explicaciones, se investiga y se comunican los resultados.'),
mk(2,'Definición operacional','Una definición operacional:','Traduce la hipótesis a procedimientos concretos que pueden medirse o manipularse',['Resume la teoría','Describe a los participantes','Interpreta los resultados'],'Hace comprobable la hipótesis.'),
mk(2,'Métodos descriptivos: estudio de caso','Un estudio de caso consiste en:','Investigar a fondo a una persona o un grupo pequeño',['Preguntar a una muestra grande','Examinar registros existentes','Asignar al azar a dos grupos'],'Aporta profundidad, pero es difícil generalizar.'),
mk(2,'Métodos descriptivos: documental','La investigación documental consiste en:','Examinar registros existentes para poner a prueba una hipótesis',['Observar en el ambiente real','Preguntar directamente a las personas','Manipular una variable'],'Su riesgo: pueden no existir datos o ser inútiles.'),
mk(2,'Experimentos: variable dependiente','La variable dependiente es la que:','Se mide como resultado',['Manipula el experimentador','Se mantiene fuera del estudio','Define al grupo control'],'Depende de lo que haga el participante.'),
mk(2,'Experimentos: grupos','El grupo experimental es el que:','Recibe el tratamiento',['No recibe ningún tratamiento','Se elige por conveniencia','Solo observa'],'El grupo de control sirve de comparación.'),
mk(2,'Réplica y significancia','Repetir una investigación para comprobar sus hallazgos se llama:','Réplica',['Hipótesis','Tratamiento','Asignación aleatoria'],'Da confianza en que el resultado no fue casual.'),
mk(2,'Investigación correlacional','La investigación correlacional busca:','Saber si dos variables se relacionan',['Probar que una causa a la otra','Describir un solo caso','Manipular una variable'],'Por eso no establece causalidad.'),
mk(3,'Ética: privacidad','El derecho a la privacidad implica que:','Se protege la información sobre la conducta de los participantes',['Se publican sus nombres','Se obliga a participar','Se oculta el objetivo siempre'],'Es una de las pautas éticas básicas junto con evitar el daño y la voluntariedad.'),
mk(3,'Sesgo experimental','Un ejemplo de sesgo experimental es que:','Las expectativas del investigador o de los participantes influyan en los resultados',['El estudio tenga un grupo control','Los participantes firmen consentimiento','La muestra sea grande'],'Amenaza la validez del experimento.'),
mk(3,'Consentimiento informado','Antes de participar, el consentimiento informado exige conocer:','Los riesgos que puede haber',['Los resultados antes de que ocurran','La identidad de los demás participantes','El pago exacto'],'También el procedimiento y el derecho a retirarse.'),
mk(3,'Diversidad de participantes','¿Cuál es el problema de estudiar solo a un grupo, por ejemplo estudiantes universitarios?','Los resultados podrían no aplicarse a otros grupos',['Se necesita más tiempo','No se puede replicar','Se rompe la privacidad'],'Por eso se buscan muestras representativas.'),
mk(3,'Placebo','Un placebo es:','Un tratamiento sin efecto activo que se usa como comparación',['Un medicamento más fuerte','Un grupo experimental','Una variable independiente'],'Ayuda a controlar el sesgo experimental.'),
mk(3,'Consumidor informado','Ser un consumidor informado de la psicología implica:','Pensar críticamente sobre la investigación',['Aceptar todo estudio publicado','Confiar solo en la intuición','Ignorar la muestra utilizada'],'Por ejemplo, preguntarse quién investigó y con qué método.')
);
const MODN=['Los psicólogos en acción','Una ciencia evoluciona','La investigación en la psicología','Cuestiones fundamentales'];
